In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
df = pd.read_csv("Reviews.csv", nrows=50000)
df

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...
...,...,...,...,...,...,...,...,...,...,...
49995,49996,B00430B73W,AKW867T7C6HF8,HWJ3,0,0,5,1261180800,Grown to really like them,My sister introduced me to these. They have be...
49996,49997,B00430B73W,A2PEHNEDMHOYTW,L. Allen,0,0,5,1258934400,Healthy Snack at a great price!,A friend recommended these bars and I fell in ...
49997,49998,B00430B73W,A2QH2KF2IAB143,"J. A. Meyers ""Jan""",0,0,5,1257379200,Raw Revolution Hazelnut Cashew,Fabulous! I take one to work with me every da...
49998,49999,B00430B73W,AMX286UGXISMA,Aaron Dragushan,0,0,4,1247702400,"fantastic, but chew carefully",I love these bars and will continue to buy the...


In [ ]:
df.shape

(50000, 10)

In [ ]:
df.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [ ]:
light_reviews = df[df['Text'].str.contains('light', case=False, na=False)]

print("Number of reviews containing 'light':")
print(len(light_reviews))

Number of reviews containing 'light':
3511


In [ ]:
for i, review in enumerate(light_reviews['Text'].head(20)):
    print(f"\nReview {i+1}:")
    print(review)
    print("-"*100)


Review 1:
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.
----------------------------------------------------------------------------------------------------

Review 2:
I got a wild hair for taffy and ordered this five pound bag. The taffy was all very enjoyable with many flavors: watermelon, root beer, melon, peppermint, grape, etc. My only complaint is there was a bit too much red/black licorice-flavored pieces (just not my particular favorites). Between me, my kids, and my husband, this lasted only two weeks! I would recommend 

In [ ]:
sentence1 = "A very delicate green tea with a smooth light taste and subtle floral tones."

sentence2 = "The packaging was broken and let too much light inside the box."

sentence3 = "This product is light and easy on the stomach."
documents = [sentence1, sentence2, sentence3]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

dense_matrix = X.toarray()

print(dense_matrix)

[[1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1]
 [1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 2 0 0 1 0 1 0]
 [1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0]]


In [ ]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("Vector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)

Vector 1: [1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1]
Vector 2: [1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 2 0 0 1 0 1 0]
Vector 3: [1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0]


In [ ]:
import numpy as np

similarity_1_2 = np.dot(vec_1, vec_2)
similarity_1_3 = np.dot(vec_1, vec_3)

print("Similarity between Sentence 1 and Sentence 2:", similarity_1_2)
print("Similarity between Sentence 1 and Sentence 3:", similarity_1_3)

Similarity between Sentence 1 and Sentence 2: 2
Similarity between Sentence 1 and Sentence 3: 2


In [ ]:
print("Vocabulary:")
print(vectorizer.get_feature_names_out())

Vocabulary:
['and' 'box' 'broken' 'delicate' 'easy' 'floral' 'green' 'inside' 'is'
 'let' 'light' 'much' 'on' 'packaging' 'product' 'smooth' 'stomach'
 'subtle' 'taste' 'tea' 'the' 'this' 'tones' 'too' 'very' 'was' 'with']


In [ ]:
import pandas as pd

feature_names = vectorizer.get_feature_names_out()

matrix_df = pd.DataFrame(
    dense_matrix,
    columns=feature_names,
    index=["Sentence 1", "Sentence 2", "Sentence 3"]
)

print(matrix_df)

            and  box  broken  delicate  easy  floral  green  inside  is  let  \
Sentence 1    1    0       0         1     0       1      1       0   0    0   
Sentence 2    1    1       1         0     0       0      0       1   0    1   
Sentence 3    1    0       0         0     1       0      0       0   1    0   

            ...  subtle  taste  tea  the  this  tones  too  very  was  with  
Sentence 1  ...       1      1    1    0     0      1    0     1    0     1  
Sentence 2  ...       0      0    0    2     0      0    1     0    1     0  
Sentence 3  ...       0      0    0    1     1      0    0     0    0     0  

[3 rows x 27 columns]


**Conclusion:**
CountVectorizer turns words into numbers based on how often they appear, but it doesn't understand their meaning.